services:
  claude-code:
    build:
      context: ..
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./workspace:/workspace
      - ./claude-config:/claude
    ports:
      - "3001:3001"
    environment:
      CLAUDE_CONFIG_DIR: /claude

