services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UBUNTU_USERNAME=${UBUNTU_USERNAME:-developer}
        - UBUNTU_PASSWORD=${UBUNTU_PASSWORD:-changeme123}
    ports:
      - "3389:3389"  # RDP port
      - "5173:5173"  # claudecodeui frontend (Vite)
      - "3000:3000"  # claudecodeui backend
    environment:
      - DISPLAY=:1
    volumes:
      - ./workspace:/workspace
    stdin_open: true
    tty: true
